# Generated by Django 2.2 on 2019-10-02 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_profile_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='circles',
            field=models.PositiveIntegerField(default=1, help_text='Number of circles completed'),
        ),
    ]
