# Generated by Django 2.2 on 2019-09-26 00:27

import coin.tools
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DownLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_visits', models.IntegerField(default=0, help_text='Total site visits')),
                ('total_referral', models.IntegerField(default=0, help_text='Total users referred')),
                ('total_users', models.IntegerField(default=0, help_text='Total registered users')),
                ('total_payouts', models.DecimalField(decimal_places=3, default=0.0, help_text='Total amount paid out', max_digits=15)),
                ('total_earnings', models.DecimalField(decimal_places=3, default=0.0, help_text='Total amount earned', max_digits=15)),
                ('total_invoiced', models.DecimalField(decimal_places=3, default=0.0, help_text='Total amount invoiced', max_digits=15)),
                ('total_balance', models.DecimalField(decimal_places=3, default=0.0, help_text='Total amount in account', max_digits=15)),
            ],
            options={
                'verbose_name_plural': 'histories',
                'ordering': ['total_balance'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.BigIntegerField(default=coin.tools.generate_invoice, editable=False, help_text='Unique invoice number', unique=True)),
                ('paid_from_wallet', models.CharField(blank=True, help_text='Bitcoin wallet address used for payment', max_length=60, null=True)),
                ('description', models.CharField(blank=True, default='', help_text='Invoice description', max_length=200, null=True)),
                ('amount', models.DecimalField(decimal_places=3, default=0.0, help_text='Total amount to pay', max_digits=15)),
                ('paid', models.BooleanField(blank=True, default=False, help_text='Is invoiced paid?', null=True)),
                ('pay', models.BooleanField(default=False, help_text='Confirm you have paid for the invoice', null=True)),
                ('pay_confirm', models.BooleanField(default=False, help_text='Receiving user confirm payment received', null=True)),
                ('issue_date', models.DateTimeField(auto_now_add=True, help_text='Date issued')),
                ('pay_date', models.DateTimeField(blank=True, help_text='Date paid', null=True)),
            ],
            options={
                'ordering': ['issue_date', '-pay_date'],
            },
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, help_text='Date joined')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=3, default=0.0, help_text='Total balance', max_digits=15)),
                ('to_earn', models.DecimalField(decimal_places=3, default=0.0, help_text='Amount to earn', max_digits=15)),
                ('to_pay', models.DecimalField(decimal_places=3, default=0.0, help_text='Amount to pay', max_digits=15)),
                ('total_payout', models.DecimalField(decimal_places=5, default=0.0, help_text='Total amount paid out', max_digits=15)),
                ('total_earned', models.DecimalField(decimal_places=5, default=0.0, help_text='Total amount ever earned', max_digits=15)),
            ],
            options={
                'ordering': ['balance'],
            },
        ),
    ]
