# Generated by Django 2.2 on 2019-09-26 00:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coin', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='user',
            field=models.ForeignKey(help_text='Wallet oowner', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='referral',
            name='referee',
            field=models.ForeignKey(blank=True, help_text='Refering user', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='referral',
            name='referred',
            field=models.ForeignKey(help_text='Referred user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoiced_to',
            field=models.ForeignKey(help_text='Invoiced user', on_delete=django.db.models.deletion.CASCADE, related_name='invoiced_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoice',
            name='issuer',
            field=models.ForeignKey(help_text='Invoice issuer', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='history',
            name='user',
            field=models.ForeignKey(help_text='User history', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='downline',
            name='leader',
            field=models.ForeignKey(help_text='Downline Leader', on_delete=django.db.models.deletion.CASCADE, related_name='downline_leader', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='downline',
            name='user1',
            field=models.ForeignKey(blank=True, help_text='First user in downline', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='downline_user1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='downline',
            name='user2',
            field=models.ForeignKey(blank=True, help_text='Second user in downline', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='downline_user2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='downline',
            name='user3',
            field=models.ForeignKey(blank=True, help_text='Third user in downline', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='downline_user3', to=settings.AUTH_USER_MODEL),
        ),
    ]
