# Generated by Django 2.2 on 2019-10-02 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin', '0004_auto_20191002_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='total_earned',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total amount ever earned', max_digits=15),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='total_payout',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total amount paid out', max_digits=15),
        ),
    ]
